server:
  port: 8060

spring:
  application:
    name: @artifactId@
  main:
    allow-bean-definition-overriding: true
dubbo:
  registry:
    #注册中心地址
#    address: N/A
    address: zookeeper://127.0.0.1:2181
#    address: 127.0.0.1 # zookeeper注册中心的地址
#    port: 2181       # zookeeper注册中心的端口
#    protocol: zookeeper
    #指定注册到zk上超时时间，ms
    timeout: 10000
  #指定dubbo使用的协议、端口
  protocol:
    name: dubbo
    port: 20880
  #指定实现服务(提供服务）的包
  scan:
    base-packages: com.zhuaer.learning.dubbo.provider.service
