
server:
  port: 8070

spring:
  application:
    name: @artifactId@
  main:
    allow-bean-definition-overriding: true
  #配置rabbitMq 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /user_center