
server:
  port: 8081

spring:
  application:
    name: @artifactId@
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8849
#        port: 客户端端口（8719）
#        client-ip: 客户端IP（指定部署springboot项目云服务器的外网IP）
#      eager: true