
server:
  port: 8081

spring:
  application:
    name: @artifactId@
  redis:
    redisson:
      # 配置单点模式
      file: "classpath:redisson.yaml"
  main:
    allow-bean-definition-overriding: true

#redisson 官网文档：https://github.com/redisson/redisson/wiki/2.-%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95#26-%E5%8D%95redis%E8%8A%82%E7%82%B9%E6%A8%A1%E5%BC%8F



##直接把全部配置写到springboot的配置文件application.yml里
#spring:
#  redis:
#    redisson:
#      config:
#        clusterServersConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: 10000
#          timeout: 3000
#          retryAttempts: 3
#          retryInterval: 1500
#          failedSlaveReconnectionInterval: 3000
#          failedSlaveCheckInterval: 60000
#          password: null
#          subscriptionsPerConnection: 5
#          clientName: null
#          loadBalancer: ！<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#          subscriptionConnectionMinimumIdleSize: 1
#          subscriptionConnectionPoolSize: 50
#          slaveConnectionMinimumIdleSize: 24
#          slaveConnectionPoolSize: 64
#          masterConnectionMinimumIdleSize: 24
#          masterConnectionPoolSize: 64
#          readMode: "SLAVE"
#          subscriptionMode: "SLAVE"
#          nodeAddresses:
#            - "redis://192.168.35.142:7002"
#            - "redis://192.168.35.142:7001"
#            - "redis://192.168.35.142:7000"
#          scanInterval: 1000
#          pingConnectionInterval: 0
#          keepAlive: false
#          tcpNoDelay: false
#        threads: 16
#        nettyThreads: 32
#        codec: !<org.redisson.codec.FstCodec> {}
#        transportMode: "NIO"