
server:
  port: 8081

spring:
  application:
    name: @artifactId@
  redis:
    redisson:
      # 配置单点模式
      file: "classpath:redisson.yaml"
  main:
    allow-bean-definition-overriding: true

#redisson 官网文档：https://github.com/redisson/redisson/wiki/2.-%E9%85%8D%E7%BD%AE%E6%96%B9%E6%B3%95#26-%E5%8D%95redis%E8%8A%82%E7%82%B9%E6%A8%A1%E5%BC%8F
