
server:
  port: 8081

spring:
  application:
    name: @artifactId@
  redis:
    #Redis数据库索引（默认为0）
    database: 5
    host: 127.0.0.1
    password:
    port: 16379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100ms
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 10000ms
  main:
    allow-bean-definition-overriding: true
