
server:
  port: 8070

spring:
  application:
    name: @artifactId@
  main:
    allow-bean-definition-overriding: true
# 是否启用内存模式（就是不安装MQ，项目启动时同时启动一个MQ实例）
  activemq:
    in-memory: true
  jms:
    pub-sub-domain: true    #false = Quene   true = Topic
#    user:
#    password:
#    broker-url: tcp://127.0.0.1:61616


#广播模式
#spring.jms.pub-sub-domain=true

#信任所有的包
#spring.activemq.packages.trust-all=true
#是否替换默认的连接池，使用ActiveMQ的连接池需引入的依赖
#spring.activemq.pool.enabled=false
