
server:
  port: 8081

spring:
  application:
    name: @artifactId@
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: product_route
#          uri: lb://product
          uri: https://www.aliyun.com/
          predicates:
            - Path=/product/**
        - id: httpbin_route
          uri: https://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
        - id: zhua_route
          uri: https://www.zhua91.com
          predicates:
            - Path=/zhua/**
        - id: test_route
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v1/test/**
          filters:
            - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8849
#      eager: true
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring.cloud.sentinel.datasource.ds2.nacos.server-addr=127.0.0.1:8848
#spring.cloud.sentinel.datasource.ds2.nacos.data-id=gateway-sentinel-degrade.properties
#spring.cloud.sentinel.datasource.ds2.nacos.namespace=0e152861-1efa-62ea-9125-e569abc29691
#spring.cloud.sentinel.datasource.ds2.nacos.group-id=DEFAULT_GROUP
#spring.cloud.sentinel.datasource.ds2.nacos.data-type=json
#spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade

